Improve initialization for extra arches
chaiNNer-org/spandrel pull request #281
Opened 2024-07-04 06:30 UTC by akx

This PR is related to https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/16144, where we have to do some contortions to install extra arches when Spandrel is late-imported.

It

1. makes the `ValueError` for duplicate architectures a specific exception type, so it can be caught...
2. ... by the new `spandrel_extra_arches.install()` convenience function, which will return False (and not raise) in case the main registry already has (any of) the arches it tries to wire up.

2024-07-07 10:08 UTC, RunDevelopment reviewed
Sorry for the delay.

There are 2 things I want to talk about:
1. I really like the `install` function, but I think its API is a little weird. It only returns `False` for a single type of failure and throws otherwise. This also contradicts the documentation of the function.

    I think a better API would be `def install(*, ignore_duplicates=False) -> None`. Basically, it throws by default, but you can use `install(ignore_duplicates=True)` to ensure that the second install is a noop.

    Implementation-wise, we just have to add a `ignore_duplicates=False` argument to `ArchRegistry#add`, and then `install` can be implemented as simply:

    ```py
    def install(ignore_duplicates: bool = False) -> None:
        """TODO: Add docs"""
        MAIN_REGISTRY.add(*EXTRA_REGISTRY, ignore_duplicates=ignore_duplicates)
    ```
2. Throwing a `DuplicateArchitectureError` is a breaking change. I don't think it's a bad change, but this is something we have to consider, especially since the need for a unique error has been diminished with the `ignore_duplicates` parameter.

2024-07-10 07:51 UTC, akx commented
> Throwing a DuplicateArchitectureError is a breaking change. 

It's not, IMO, unless you're catching things in a particularly weird way (like, `if type(exc) is ValueError` weird). Unless I'm missing something?

We used to throw `ValueError`, now we throw `DuplicateArchitectureError` which derives from `ValueError`, so if you have a `except ValueError`, the new exception would still be caught too.

2024-07-10 10:13 UTC, RunDevelopment commented
> It's not [...]. We used to throw `ValueError`, now we throw `DuplicateArchitectureError` which derives from `ValueError`

You're absolutely correct. I overlooked that. Please ignore point 2.

2024-07-11 09:26 UTC, RunDevelopment requested changes
Just 2 minor nits.

2024-07-11 09:26 UTC, RunDevelopment commented on tests/util.py
> +assert not spandrel_extra_arches.install(ignore_duplicates=True)
Having functions with side effects in [`assert`](https://docs.python.org/3/reference/simple_stmts.html#assert) seems like a bad idea to me.

```suggestion
# The asserts check that the install function first does return
# the newly installed architectures and then does not return them
# when requested to ignore duplicates.
_installed_extras = spandrel_extra_arches.install()
assert len(_installed_extras) > 0
assert len(spandrel_extra_arches.install(ignore_duplicates=True)) == 0
```

2024-07-11 09:26 UTC, RunDevelopment commented on libs/spandrel_extra_arches/spandrel_extra_arches/__helper.py
> +def install(*, ignore_duplicates: bool = False) -> list:
That `list` should be typed. You just need to add `from __future__ import annotations` to make this work in py 3.8 and 3.9.

```suggestion
def install(*, ignore_duplicates: bool = False) -> list[ArchSupport]:
```

2024-07-11 12:30 UTC, merged